AWSTemplateFormatVersion: 2010-09-09
Description: Create IAM Policy for Common permissions boundary

Resources:
  IamManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Common permissions boundary
      ManagedPolicyName: PB-Policy
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAllService
            Effect: Allow
            Action: "*"
            Resource: "*"

          - Sid: DenyIAMUserIAMGroup
            Effect: Deny
            Action:
              - iam:CreateUser
              - iam:CreateLoginProfile
              - iam:CreateAccessKey
              - iam:UpdateUser
              - iam:DeleteUser
              - iam:CreateGroup
              - iam:UpdateGroup
              - iam:DeleteGroup
              - iam:AddUserToGroup
              - iam:RemoveUserFromGroup
              - iam:AttachUserPolicy
              - iam:DetachUserPolicy
              - iam:PutUserPolicy
              - iam:DeleteUserPolicy
              - iam:AttachGroupPolicy
              - iam:DetachGroupPolicy
              - iam:PutGroupPolicy
              - iam:DeleteGroupPolicy
            Resource: "*"

          - Sid: DenyCreateIAMRoleWithoutPBPolicy
            Effect: Deny
            Action:
              - iam:CreateRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:PutRolePermissionsBoundary
            Resource: "*"
            Condition:
              StringNotEquals:
                iam:PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/PB-Policy

          - Sid: DenyDeletePBPolicyFromIAMRole
            Effect: Deny
            Action:
              - iam:DeleteRolePermissionsBoundary
            Resource: "*"
            Condition:
              StringEquals:
                iam:PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/PB-Policy

          - Sid: DenyModifyDeletePBPolicy
            Effect: Deny
            Action:
              - iam:CreatePolicyVersion
              - iam:DeletePolicy
              - iam:DeletePolicyVersion
              - iam:SetDefaultPolicyVersion
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:policy/PB-Policy
