services:
  vscode-ssh:
    build:
      context: ./
      dockerfile: Dockerfile
    image: custom/vscode-ssh:latest
    container_name: vscode-ssh
    hostname: vscode-ssh
    restart: always
    secrets:
      - CHANGE_PW
      - SSH_PUBKEY
    volumes:
      - type: bind
        source: "./bind/projects/"
        target: "/projects/"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:9101
        tag: "docker.{{.Name}}"
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "10022:22"
    networks:
      - frontend

networks:
  frontend:
    external: true

secrets:
  CHANGE_PW:
    file: ./bind/secrets/PW.txt
  SSH_PUBKEY:
    file: ./bind/secrets/PUBKEY.txt
